import { LeaveRequest } from "../types/leave";

const API_URL = "http://localhost:3000/api/leave";

/**
 * GET /api/leave
 * Fetches all leave requests from the backend database.
 */
export async function fetchLeaveRequests(): Promise<LeaveRequest[]> {
    const res = await fetch(API_URL);
    if (!res.ok) throw new Error("Failed to fetch leave requests.");
    return res.json();
}

/**
 * POST /api/leave
 * Sends a new leave request to the backend. The id, status, createdAt, and
 * updatedAt fields are generated by the database — do not include them here.
 */
export async function addLeaveRequest(
    request: Omit<LeaveRequest, "id" | "status" | "createdAt" | "updatedAt">
): Promise<LeaveRequest> {
    const res = await fetch(API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(request),
    });
    if (!res.ok) {
        const err = await res.json();
        throw new Error(err.errors?.[0] ?? "Failed to submit leave request.");
    }
    return res.json();
}

/**
 * DELETE /api/leave/:id
 * Permanently removes a leave request from the database.
 */
export async function deleteLeaveRequest(id: number): Promise<void> {
    const res = await fetch(`${API_URL}/${id}`, { method: "DELETE" });
    if (!res.ok) throw new Error(`Failed to delete leave request with id ${id}.`);
}
